/**
 * Seed sentence ideas for players who freeze up on the first round.
 * Deliberately absurd — the funnier the seed, the funnier the chain falls apart.
 */
export const PROMPTS = [
  'A cat riding a motorbike to work',
  'A grandma winning a breakdance battle',
  'A penguin sunbathing in the desert',
  'A robot crying over burnt toast',
  'A shark wearing roller skates',
  'A wizard stuck in a traffic jam',
  'A giraffe trying to use an ATM',
  'A pizza slice running a marathon',
  'An octopus teaching yoga',
  'A dinosaur applying for a bank loan',
  'A snowman on a beach holiday',
  'A frog conducting an orchestra',
  'A pirate scared of water',
  'A cow jumping over a satellite',
  'A vampire dentist at work',
  'A hamster lifting a truck',
  'A cloud that refuses to rain',
  'A banana slipping on a person',
  'A goldfish walking a dog',
  'A knight fighting a vacuum cleaner',
  'A bee stuck in a lift with a bear',
  'An alien reviewing street food',
  'A turtle winning a Formula 1 race',
  'A ghost afraid of the dark',
  'A chef cooking with a flamethrower',
  'A sloth late for its own wedding',
  'A pigeon running a coffee shop',
  'A yeti getting a haircut',
  'A duck in a business meeting',
  'A cactus giving someone a hug',
  'A monkey doing tax returns',
  'A whale in a swimming pool',
  'A superhero who can only whisper',
  'A crocodile brushing its teeth',
  'A donkey playing electric guitar',
  'A snail winning a staring contest',
  'A koala driving a school bus',
  'An elephant tiptoeing past a sleeping mouse',
  'A skeleton doing a photoshoot',
  'A worm lifting weights at the gym',
  'A parrot arguing with a mirror',
  'A bear ordering bubble tea',
  'A squirrel hacking a computer',
  'A astronaut who forgot the way home',
  'A hedgehog popping balloons by accident',
  'A llama modelling on a runway',
  'A crab playing the piano',
  'A owl who overslept',
  'A dragon lighting birthday candles',
  'A rabbit stuck in a vending machine',
];

export function randomPrompt() {
  return PROMPTS[Math.floor(Math.random() * PROMPTS.length)];
}
